import {keywordCases} from './keywords.js';
import {timingCases} from './timing.js';
import {assetCases} from './assets.js';
import {scenarioCases} from './scenarios.js';
import {weaponCases} from './weapons.js';
import {skillCases} from './skills.js';
import {numberCases} from './numbers.js';
import {restorationCases} from './restoration.js';
import {lifecycleCases} from './lifecycles.js';
export const auditCases=[...keywordCases,...timingCases,...assetCases,...weaponCases,...skillCases,...numberCases,...scenarioCases,...restorationCases,...lifecycleCases];
