import { useState } from 'react';
import type { Catalog, HistoryEntry, SessionView } from '../shared/types';
import { dateTime } from './api';
import { Icon, Modal } from './components';

export interface Invitations { seats:{investigatorId:string;name:string;token:string;path:string}[] }
export interface Tunnel {status:'stopped'|'starting'|'running'|'error';url:string|null;error:string|null}

export function HistoryDialog({session,entries,busy,rollback,onClose}:{session:SessionView;entries:HistoryEntry[];busy:boolean;rollback:(id:string)=>void;onClose:()=>void}) {
  const [selected,setSelected]=useState<string|null>(null);
  const current=entries.find(h=>h.id===session.checkpointId);
  const branches=new Set(entries.map(h=>h.branchId));
  return <Modal title="The investigation's history" eyebrow={`${entries.length} checkpoints · ${branches.size} ${branches.size===1?'branch':'branches'}`} onClose={onClose} wide><p className="muted">Restore a complete snapshot of the table. Restoring creates a new branch and preserves everything that followed.</p><div className="history-list">{[...entries].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||b.revision-a.revision).map(entry=><button key={entry.id} className={`history-entry ${entry.id===session.checkpointId?'current':''} ${selected===entry.id?'selected':''}`} onClick={()=>setSelected(entry.id)} disabled={entry.id===session.checkpointId}><span className="history-node"/><div><strong>{entry.label}</strong><span>{dateTime(entry.createdAt)} · Revision {entry.revision} · Branch {entry.branchId.slice(0,6)}</span><small title={entry.stateHash}>State {entry.stateHash.slice(0,12)}{entry.parentId?` · Parent ${entry.parentId.slice(0,6)}`:' · Initial snapshot'}</small></div>{entry.id===session.checkpointId?<span className="tag success">Current</span>:<span>↶</span>}</button>)}</div>{!entries.length&&<p className="muted">Loading checkpoints…</p>}<div className="modal-footer"><p className="fine-print">{selected?`Selected: ${entries.find(h=>h.id===selected)?.label}`:current?'Select an earlier checkpoint, including one on another branch.':'Loading the current branch…'}</p><button className="button primary" disabled={busy||!selected} onClick={()=>{if(selected)rollback(selected);}}><Icon name="history" size={17}/>Restore checkpoint</button></div></Modal>;
}

export { LogDialog } from './CampaignLogDialog';

export function SaveDialog({session,busy,save,onClose}:{session:SessionView;busy:boolean;save:(name:string)=>void;onClose:()=>void}) {
  const [name,setName]=useState(`${session.name} — ${session.phase==='ready'?'Table ready':'Opening hands'}`);
  return <Modal title="Name this moment" eyebrow={`Checkpoint ${session.revision}`} onClose={onClose}><form onSubmit={e=>{e.preventDefault();if(name.trim())save(name.trim());}}><label>Save name<input value={name} onChange={e=>setName(e.target.value)} required maxLength={100} autoFocus/></label><p className="muted">Your game already autosaves. A named save gives this checkpoint a place in the Load / replay menu.</p><div className="modal-footer"><button type="button" className="button subtle" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy||!name.trim()}><Icon name="save" size={17}/>Save checkpoint</button></div></form></Modal>;
}

export function InviteDialog({invitations,session,catalog,tunnel,busy,regenerate,toggleTunnel,notify,onClose}:{invitations:Invitations|null;session:SessionView;catalog:Catalog;tunnel:Tunnel;busy:boolean;regenerate:()=>void;toggleTunnel:(action:'start'|'stop')=>void;notify:(text:string)=>void;onClose:()=>void}) {
  const [publicLinks,setPublicLinks]=useState(true);
  const base=publicLinks&&tunnel.url?tunnel.url:location.origin;
  const copy=async(value:string)=>{try{await navigator.clipboard.writeText(value);notify('Invitation copied.');}catch{notify('Clipboard is unavailable. Select and copy the invitation link.');}};
  return <Modal title="Invite your investigators" eyebrow="Separate tabs, one shared table" onClose={onClose} wide><p className="muted">Each invitation opens a private player seat. Keep this host tab open to manage the table.</p><div className="tunnel-panel"><div><Icon name="people" size={25}/><div><h3>Play over the internet</h3><p>{tunnel.status==='running'?'Your Cloudflare tunnel is ready. Share the player links below.':tunnel.status==='starting'?'Cloudflare is connecting…':'Start a Cloudflare tunnel to invite players outside your network.'}</p></div></div><button className={`button ${tunnel.status==='running'?'secondary':'primary'} small`} disabled={busy||tunnel.status==='starting'} onClick={()=>toggleTunnel(tunnel.status==='running'?'stop':'start')}>{tunnel.status==='running'?'Stop tunnel':tunnel.status==='starting'?'Connecting…':'Start tunnel'}</button></div>{tunnel.error&&<p className="inline-warning">{tunnel.error}</p>}{tunnel.url&&<div className="link-mode"><label className="radio-label"><input type="checkbox" checked={publicLinks} onChange={e=>setPublicLinks(e.target.checked)}/>Use internet invitation links</label><span className="fine-print">{tunnel.url}</span></div>}<div className="invite-seats">{invitations?invitations.seats.map(seat=>{const investigator=session.investigators.find(i=>i.id===seat.investigatorId);const link=new URL(seat.path,base).href;return <section className="panel invite-seat" key={seat.investigatorId}><div className="invite-seat-heading"><span className="seat-disc">{investigator?.seat??1}</span><div><strong>{seat.name}</strong><span>{catalog.cards[investigator?.investigatorCode||'']?.name}</span></div></div><label className="sr-only" htmlFor={`invite-${seat.investigatorId}`}>Invitation for {seat.name}</label><input id={`invite-${seat.investigatorId}`} readOnly value={link} onFocus={e=>e.target.select()}/><div className="invite-actions"><button className="button secondary small" onClick={()=>void copy(link)}><Icon name="link" size={16}/>Copy link</button><button className="button subtle small" onClick={()=>window.open(new URL(seat.path,location.origin).href,'_blank','noopener')}>Open tab ↗</button><button className="button subtle small" onClick={()=>window.open(new URL(seat.path,location.origin).href,`arkham-${seat.investigatorId}`,'popup,width=1440,height=940,noopener')}>Open window ↗</button></div></section>;}):<p className="muted">Creating player invitations…</p>}</div><div className="modal-footer"><p className="fine-print">Invitations grant access to one player seat. Replacing invitations revokes the previous links.</p><button className="button subtle small" disabled={busy} onClick={regenerate}><Icon name="refresh" size={15}/>Replace invitations</button></div></Modal>;
}
